apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: default
  student_name: "Voevodin Alexey" # my name
spec:
  ports:
    - name: web
      port: 9093
      targetPort: 9093
  selector: {}
